---
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install dependencies
        run: go get -t -v ./...
        working-directory: ./builder
      - name: Test
        run: go test -coverprofile=coverage.out ./...
        working-directory: ./builder
      - name: Coverage
        run: go tool cover -func=coverage.out
        working-directory: ./builder
